### ISSUE TITLE
`totalRecords` must be a finite integer 

### ISSUE THREAD

**Issue by jeacott** [backbone-paginator/backbone-pageable#146]
Hi All,
  I'm using servermode, and have overrides as follows:

```
 parseRecords: function (resp) {
          return resp.content;
        },
        parseState: function (resp, queryParams, state, options) {
              return {totalRecords: resp.totalElements -1 };
        },
        parseLinks: function (resp, xhr) {
            return {
                "next": this.url()
                };
          }
```

when calling collection.create(...)  with wait:false, this works fine.
but when I set create({...},{wait:true}); the parseState method gets called with the returned entity, which is not a pageResult, and does not have a totalElements field and so I get an
'Uncaught TypeError: `totalRecords` must be a finite integer '

thoughts?

**Comment by wyuenho** [comment]
I can't reproduce this. Parse shouldn't be called in both instances. It would help if you could provide a jsfiddle.

BTW, you don't need to override parseLinks for server mode. It'll never get called.

**Comment by jeacott** [comment]
ok, so the reason parse is being called is because in backbone 1.1 line 472:
      // After a successful server-side save, the client is (optionally)
      // updated with the server-side state.
      if (options.parse === void 0) options.parse = true;

at this point if I step through this, options.parse is set to true,  so parse is eventually called.
I'm not sure why you can't reproduce this.
after tracing this, if I send parse:false as an option in the create it fixes the problem, but I'm not sure I should need to.

**Comment by wyuenho** [comment]
A better question is, why is your model's `parse` method the same as the collection's `parse` method? Backbone is clearly only calling the model's parse method.

https://github.com/backbone-paginator/backbone-pageable/blob/master/test/vendor/backbone.js#L881

Have you accidently copied the collection's parse to the model?

**Comment by chris-h-sg** [comment]
I think this is a problem with Backbone: https://github.com/jashkenas/backbone/issues/2824

The issue has been fixed over there, but not released yet. To get around this, call
`collection.create({}, {wait: true, parse: false})`.

**Comment by jeacott** [comment]
nope, but your comment did make me realise whats going on.
Its a backbone.relational collection, and it does this:

```
Backbone.Collection.prototype.set = function( models, options ) {
        // Short-circuit if this Collection doesn't hold RelationalModels
        if ( !( this.model.prototype instanceof Backbone.RelationalModel ) ) {
            return set.apply( this, arguments );
        }

        if ( options && options.parse ) {
            models = this.parse( models, options );
        }
```

and thats the parse thats getting run.

**Comment by wyuenho** [comment]
Mmmm. I need more testing to confirm this, it actually does sound like it's a manifestation of  jashkenas/backbone#2824.

As a side note, @jeacott you are using a project that silently monkey patches Backbone.Collection? Backbone's continuous passing of a mutable options object causes enough subtle bugs already, you want to use a project that implicitly alters behavior for _every_ Backbone.Collection instances?

Have you tried [backbone-associations](https://github.com/dhruvaray/backbone-associations) instead?

**Comment by jeacott** [comment]
fair comment, I'm still getting used to the world of javascript, and backbone.relational certainly has its share of issues. I'll check out associations. 
thank you.

**Comment by wyuenho** [comment]
Yep this is a backbone bug. Let me know if you still have this problem after upgrading to backbone 1.1.1+

**Comment by jeacott** [comment]
upgraded to 1.1.2 and problem has evaporated :)  thank you for looking into this.
